url: "https://spicata.github.io/mint-fresh-notes/"
baseurl: /mint-fresh-notes/

title: "mint fresh notes :)"
description: "Where I study, post old things, post new things, and more :)"

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  authors:
    output: true
  notes:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-wikilinks
