url: "https://spicata.github.io"
baseurl: /mint-fresh-notes/

title: "mint fresh notes :)"
description: "Where I study, post old things, post new things, and more :)"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  authors:
    output: true
  notes:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
